server:
  port: 8080
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
    encoding:
      enabled: true
      charset: utf-8
      force: true
  tomcat:
    basedir: ./tomcat
    accesslog:
      buffered: true
      directory: ./logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      prefix: access_log
      rename-on-rotate: false
      pattern: common
      request-attributes-enabled: false
      rotate: true
      max-days: 60
    threads:
      max: 500
    uri-encoding: utf-8
logging:
  config: classpath:log4j2.xml
conn:
  tidb-one: "AC86DtNU1f5sKjvJAKvjWF+Zl5ECLzgMAC0/CQUsPgoELTgRAysnCwE3NQtOKDkMAWJlX0dFaUFFeGdZTmpiWFFEfV1WelcMACw6DwJgZE5FbFlZUnhIRl1/c1AeKT0HAC8iDQIvOQ0E"
  tidb-two: "FDcJCpF7x3aRFJK9HAmKHpwZ3cEWNwsIFDUMDRE0DQ4QNQsVFzMUDBAvDw9aMAoIFXpWW1NdWkVRYFRdWnJRXEVcTllCYmQIFDQJCxZ4V0pRdGpdRmB7QklnQFQKMQ4DFDcRCRY3CgkQ"
  hl-hs: "MSo+BiK5TV3RLXtuH/SskBfVtYgzKjwEMSg7ATQpOgI1KDwZMiAjAzYlJwQ7ZT4HMC1wXXZAbFB0eVJHZn1jW3ViY0NZf21BY0d9UmJ9dntydENdd1J5dyM5PwM3"
appConfig:
  version: '@project.version@'
  timestamp : '@timestamp@'
  swagger: false