server:
  port: 8080
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
    encoding:
      enabled: true
      charset: utf-8
      force: true
  tomcat:
    basedir: ./tomcat
    accesslog:
      buffered: true
      directory: ./logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      prefix: access_log
      rename-on-rotate: false
      pattern: common
      request-attributes-enabled: false
      rotate: true
      max-days: 60
    threads:
      max: 500
    uri-encoding: utf-8
logging:
  config: classpath:log4j2.xml
appConfig:
  version: '@project.version@'
  timestamp : '@timestamp@'
evssDb:
  zgConnStr: IiQQKwCfpb0hMLNbjih64W5J1i0gJBIpIiYVLCcnFC8mZUd3fGJGcm5hVnY+dEx0byYRKCBtaldicFFhKVhITG1cbmxzZ1shXH90ZnlGZlhwYldAfEA=
  jmConnStr: AzQ+CSGPi58AIJ15rzhUw09Z+A8BNDwLAzY7DgY3Og0HdWlVXXJoUE9xeFQfZGJWTjY/CgF9RHVDYH9DCEhmbkxMQE5Sd3UDfW9aRFhWSHpRcnliXVA=