server:
  port: 8090
appConfig:
  swagger: true
conn:
  tidb-one: "DTgvHBp4Bap4zn92xR0PbpN9ddwPOC0eDToqGwg7KxgJZmReTWYyW0liaFhdJX9BUXUuHAk7ZUZFb2RbWmd6UlN1f1JObHNLQjp6T14+LEgIPClKBmh+HAg="
  tidb-two: "DTgvHBp4Bap4zn92xR0PbpN9ddwPOC0eDToqGwg7KxgJZmReTWYyW0liaFhdJX9BUXUuHAk7ZUZFb2RbWmd6UlN1f1JObHNLQjp6T14+LEgIPClKBmh+HAg="
  hl-hs: "DTgvHBp4Bap4zn92xR0PbpN9ddwPOC0eDToqGwg7KxgJZmReTWYyW0liaFhdJX9BUXUuHAk7ZUZFb2RbWmd6UlN1f1JObHNLQjp6T14+LEgIPClKBmh+HAg="